#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Keep a named planted defect for every declared core or example test."""
import argparse
import json
from pathlib import Path
import traceability
import test_registry
from needle_audit import validate_needles

ROOT = Path(__file__).resolve().parents[1]


def canonical(name):
    return test_registry.canonical(name)


def validate_targets(tests, mutations):
    named = {canonical(k['test']) for m in mutations for k in m['kills']}
    return ['unproven test or unknown mutation target: ' + name
            for name in sorted(named ^ set(tests))]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    parser.add_argument('--build', type=Path, default=Path('build-registration'))
    parser.add_argument('--jobs', type=int, default=16)
    args = parser.parse_args()
    mutations = json.loads((ROOT / 'tests/mutations.json').read_text())
    if validate_needles(mutations):
        raise RuntimeError(validate_needles(mutations))
    names = [m['name'] for m in mutations]
    if not (len(names) == len(set(names))):
        raise RuntimeError('duplicate mutation name')
    rows = []
    tests = {}
    for path in sorted((ROOT / 'tests').glob('test_*.cpp')):
        for name, ids, line in traceability.inventory(path.read_text()):
            tests[name] = (path, ids, line)
    errors = test_registry.reconcile([(name, *data[1:]) for name, data in tests.items()],
                                    test_registry.read_build(ROOT, args.build, args.jobs))
    if errors:
        raise RuntimeError(errors)
    if validate_targets(tests, mutations):
        raise RuntimeError(validate_targets(tests, mutations))
    text = '# Test defects\n\nGenerated by [test_inventory.py](../scripts/test_inventory.py).\nEvery test declaration has at least one named defect in the [campaign](../tests/mutations.json).\nThe campaign requires that named assertion to fail in a completed test run.\nA build error, timeout, crash or unrelated failure never counts as a caught plant.\nParameterized declarations expand at runtime; release and debug re-entry use separate binaries.\nThe [traceability matrix](TRACEABILITY.md) maps these tests to clauses.\n\n| Test | Defect caught | Requirements |\n|---|---|---|\n'
    for name, (path, ids, line) in sorted(tests.items()):
        plants = [m['name'] for m in mutations if any(canonical(k['test']) == name for k in m['kills'])]
        text += f'| [{name}](../tests/{path.name}#L{line}) | ' + '; '.join(plants) + ' | ' + ', '.join(ids) + ' |\n'
    output = ROOT / 'docs/TESTS.md'
    if args.write:
        output.write_text(text)
    elif not output.exists() or output.read_text() != text:
        raise SystemExit('test inventory is stale')
    print(f'test sensitivity: {len(tests)} declarations, {len(mutations)} plants')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
