#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate and check requirement-to-test links from test annotations."""
import argparse
import json
from pathlib import Path
import re
import test_registry

ROOT = Path(__file__).resolve().parents[1]


def inventory(text):
    rows = []
    # Preserve offsets while hiding comments and literals. Registration is the
    # authority: unsupported macros cannot silently vanish from the inventory.
    token = r'R"([^ ()\\\t\r\n]*)\(.*?\)\1"|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|/\*.*?\*/|//[^\n]*'
    code = re.sub(token, lambda m: re.sub(r'[^\n]', ' ', m[0]), text, flags=re.S)
    pattern = r'\bTEST(?:_F|_P)?\s*\(\s*(\w+)\s*,\s*(\w+)\s*\)'
    for match in re.finditer(pattern, code):
        n = text.count('\n', 0, match.start())
        lines = text[:match.start()].splitlines()
        before = next((line.strip() for line in reversed(lines) if line.strip()), '')
        annotation = re.fullmatch(r'//\s*REQ:\s*(.*)', before)
        ids = [value.strip() for value in annotation[1].split(',')] if annotation else []
        rows.append((match[1] + '.' + match[2], ids, n + 1))
    return rows


def clauses(record):
    return '; '.join(f"[{part['text']}]({part['url']})" for part in record['clauses'])


def validate(requirements, rows):
    known = {r["id"] for r in requirements}
    errors = []
    if len(known) != len(requirements):
        errors.append("duplicate requirement ID")
    used = set()
    names = set()
    for name, ids, _ in rows:
        if name in names:
            errors.append("duplicate test: " + name)
        names.add(name)
        if not ids:
            errors.append("untraced test: " + name)
        for req in ids:
            if req not in known:
                errors.append("unknown requirement: " + req)
            used.add(req)
    errors += ["untested requirement: " + req for req in sorted(known - used)]
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    parser.add_argument('--build', type=Path, default=Path('build-registration'))
    parser.add_argument('--jobs', type=int, default=16)
    args = parser.parse_args()
    if args.selftest:
        reqs = [{"id": "R1"}]
        assert not validate(reqs, inventory("// REQ: R1\nTEST(S, T) {}"))
        assert validate(reqs, inventory("// REQ: WRONG\nTEST(S, T) {}"))
        assert validate(reqs, inventory("TEST(S, T) {}"))
        assert validate(reqs, [])
        for declaration in (' TEST(S, T)', '  TEST(\n S,\n T\n )'):
            assert validate(reqs, inventory('// REQ: WRONG\n' + declaration + ' {}'))
            assert not validate(reqs, inventory('// REQ: R1\n' + declaration + ' {}'))
        assert test_registry.reconcile([], ['S.T'])
        print("traceability: unknown ID, untraced test and untested requirement controls refused")
    reqs = json.loads((ROOT / "docs/requirements.json").read_text())
    rows = []
    locations = {}
    for path in sorted((ROOT / "tests").glob("test_*.cpp")):
        found = inventory(path.read_text())
        rows += found
        locations.update({name: f"../tests/{path.name}#L{line}" for name, _, line in found})
    errors = validate(reqs, rows)
    errors += test_registry.reconcile(rows, test_registry.read_build(ROOT, args.build, args.jobs))
    if errors:
        print("\n".join(errors))
        return 1
    text = "# Traceability\n\nGenerated by [traceability.py](../scripts/traceability.py).\nEdit [requirement records](requirements.json) and the test annotations.\nSee [requirements](REQUIREMENTS.md) for scope and [test defects](TESTS.md) for sensitivity.\n\n| Requirement | Clause | Tests |\n|---|---|---|\n"
    for r in reqs:
        tests = [f"[{name}]({locations[name]})" for name, ids, _ in rows if r['id'] in ids]
        text += f"| {r['id']} | {clauses(r)} | " + "; ".join(tests) + " |\n"
    path = ROOT / "docs/TRACEABILITY.md"
    if args.write:
        path.write_text(text)
    elif not path.exists() or path.read_text() != text:
        print("traceability matrix is stale")
        return 1
    print(f"traceability: {len(reqs)} requirements; {len(rows)} test declarations")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
