#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate and check requirement-to-test links from test annotations."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def inventory(text):
    rows = []
    lines = text.splitlines()
    for n, line in enumerate(lines):
        match = re.match(r"TEST(?:_F|_P)?\((\w+),\s*(\w+)\)", line)
        if not match:
            continue
        before = lines[n - 1] if n else ""
        ids = before.removeprefix("// REQ: ").split(", ") if before.startswith("// REQ: ") else []
        rows.append((match[1] + "." + match[2], ids, n + 1))
    return rows


def validate(requirements, rows):
    known = {r["id"] for r in requirements}
    errors = []
    if len(known) != len(requirements):
        errors.append("duplicate requirement ID")
    used = set()
    names = set()
    for name, ids, _ in rows:
        if name in names:
            errors.append("duplicate test: " + name)
        names.add(name)
        if not ids:
            errors.append("untraced test: " + name)
        for req in ids:
            if req not in known:
                errors.append("unknown requirement: " + req)
            used.add(req)
    errors += ["untested requirement: " + req for req in sorted(known - used)]
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.selftest:
        reqs = [{"id": "R1"}]
        assert not validate(reqs, inventory("// REQ: R1\nTEST(S, T) {}"))
        assert validate(reqs, inventory("// REQ: WRONG\nTEST(S, T) {}"))
        assert validate(reqs, inventory("TEST(S, T) {}"))
        assert validate(reqs, [])
        print("traceability: unknown ID, untraced test and untested requirement controls refused")
    reqs = json.loads((ROOT / "docs/requirements.json").read_text())
    rows = []
    locations = {}
    for path in sorted((ROOT / "tests").glob("test_*.cpp")):
        found = inventory(path.read_text())
        rows += found
        locations.update({name: f"../tests/{path.name}#L{line}" for name, _, line in found})
    errors = validate(reqs, rows)
    if errors:
        print("\n".join(errors))
        return 1
    text = "# Traceability\n\nGenerated by [traceability.py](../scripts/traceability.py).\nEdit [requirement records](requirements.json) and the test annotations.\nSee [requirements](REQUIREMENTS.md) for scope and [test defects](TESTS.md) for sensitivity.\n\n| Requirement | Clause | Tests |\n|---|---|---|\n"
    for r in reqs:
        tests = [f"[{name}]({locations[name]})" for name, ids, _ in rows if r['id'] in ids]
        text += f"| {r['id']} | [{r['clause']}]({r['links'][0]}) | " + "; ".join(tests) + " |\n"
    path = ROOT / "docs/TRACEABILITY.md"
    if args.write:
        path.write_text(text)
    elif not path.exists() or path.read_text() != text:
        print("traceability matrix is stale")
        return 1
    print(f"traceability: {len(reqs)} requirements; {len(rows)} test declarations")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
